# (string) Title of your wiki
title: BuildCollection
description: TD2 Builds and Docs

repository: TD2Builds/BuildCollection

remote_theme: rundocs/jekyll-rtd-theme

nav_version: true

readme_index:
  with_frontmatter: true

sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

baseurl: "/BuildCollection"
url: "td2builds.github.io"
#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

# inc_before_toc :
# inc_after_toc :
# inc_before_content :
# inc_after_content :
# inc_before_footer :
# inc_after_footer :
# inc_before_head :
# inc_after_head :
# inc_before_meta :
# inc_after_meta :
# inc_before_scripts :
# inc_after_scripts :
# inc_before_styles :
# inc_after_styles :
# inc_before_header :
# inc_after_header :
# inc_before_tail :
# inc_after_tail :
# inc_before_tools :
# inc_after_tools :

# inc_before_page_list :
# inc_after_page_list :
# inc_before_post_list :
# inc_after_post_list :
